fix: return environments keyed by environment type
salesforcecli/plugin-env pull request #148
Opened 2021-09-22 19:36 UTC by peternhale

### What does this PR do?
Reorganizes list data from array to object, keyed by env type
### What issues does this PR fix or reference?
@W-9922044@

2021-09-22 19:42 UTC, mdonnalley requested changes

2021-09-22 19:42 UTC, mdonnalley commented on src/commands/env/list.ts
> +            Object.entries(columns).some(([, value]) => {
can you extract this to a method so that it's easier to read?

2021-09-22 21:09 UTC, jshackell-sfdc commented on messages/list.md
> +The columns specified on the command line (%s) are not present in Environment "%s".
```suggestion
The columns you specified (%s) aren't available in the table for environment "%s".
```

2021-09-23 15:18 UTC, mdonnalley approved these changes

2021-09-23 16:50 UTC, merged