Sm/fancy-flags
salesforcecli/plugin-env pull request #240
Opened 2022-02-28 20:36 UTC by mshanemc

### What does this PR do?
dryer delete confirmations
use the new sfdx flags

### What issues does this PR fix or reference?
@W-10766801@ is the flags WI https://github.com/salesforcecli/sf-plugins-core/pull/32

this is an update to @W-10657714@ for the delete functinonality to use the new flags

2022-03-03 21:50 UTC, peternhale requested changes

2022-03-03 21:50 UTC, peternhale commented on src/commands/env/delete/sandbox.ts
> +    if (flags['no-prompt'] || (await confirm(messages.getMessage('prompt.confirm', [org.getUsername()])))) {
@mshanemc should be using prompter instance available via `this.prompter`

2022-03-03 21:50 UTC, peternhale commented on src/commands/env/delete/scratch.ts
> +    if (flags['no-prompt'] || (await confirm(messages.getMessage('prompt.confirm', [org.getUsername()])))) {
Same here `this.prompter`

2022-03-15 20:23 UTC, RodEsp requested changes
Looks good overall 👍🏼
Just a little nitpick on some duplicated license text.

2022-03-15 20:23 UTC, RodEsp commented on src/commands/env/delete/sandbox.ts
> + */
```suggestion
/*
 * Copyright (c) 2021, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
```

2022-03-16 15:12 UTC, RodEsp submitted a review, later dismissed

2022-03-16 17:00 UTC, peternhale submitted a review, later dismissed

2022-03-16 17:54 UTC, mshanemc commented on tsconfig.json
> +    }
`error TS2742: The inferred type of 'flags' cannot be named without a reference to '@salesforce/sf-plugins-core/node_modules/@oclif/core/lib/interfaces'. This is likely not portable. A type annotation is necessary.`

TS gets confused without it, similar to https://github.com/salesforcecli/plugin-source/blob/main/tsconfig.json, when there's other oclif/core in modules (like sf-plugin-core) even when they're the same version.

Definitely helps when doing yarn link locally

2022-03-16 17:56 UTC, mshanemc commented on tsconfig.json
> +    }
happy to try without it once the sf-plugin-core get merged but you'll need it for testing

2022-03-16 17:57 UTC, RodEsp commented on tsconfig.json
> +    }
Weird. Yeah, let's try it without after the `sf-plugin-core` PR gets merged.

2022-03-17 18:20 UTC, RodEsp approved these changes

2022-03-17 18:51 UTC, merged