feat: scratch org async/resume
salesforcecli/plugin-env pull request #267
Opened 2022-04-06 17:32 UTC by mshanemc

requires https://github.com/forcedotcom/sfdx-core/pull/551
### What does this PR do?
--async on scratch create
resume command

### What issues does this PR fix or reference?
[@W-10657657@](https://gus.lightning.force.com/a07EE00000m2WwPYAU)

2022-04-12 20:01 UTC, peternhale requested changes

2022-04-12 20:36 UTC, mshanemc commented on messages/create_scratch.md
> +# timeoutUnexpected
looks like I didn't use it at all (well, technically it moved to core.  so deleting)

2022-04-12 20:45 UTC, mshanemc commented on src/commands/env/create/scratch.ts
> +        this.error('The scratch org did not complete within your wait time', { code: '69', exit: 69 });
Huh....you may have some code missing in your sandbox PR.  I see this one as an SfError https://github.com/salesforcecli/plugin-env/blob/8c80ebc35ed0bec25a42b359dfd693a81eb6ff1d/src/shared/sandboxCommandBase.ts#L140

that you catch and throw at

https://github.com/salesforcecli/plugin-env/blob/8c80ebc35ed0bec25a42b359dfd693a81eb6ff1d/src/commands/env/create/sandbox.ts#L192

FWIW I don't expect my scratch orgs to time out.  It's great that it's not a complete brick now thanks to `resume`, but if I didn't say `--async` I expect it to finish.

2022-04-12 20:53 UTC, peternhale commented on src/commands/env/create/scratch.ts
> +        this.error('The scratch org did not complete within your wait time', { code: '69', exit: 69 });
The revelation of how I treat timeouts has yet to be pushed to git. That handle function no longer exists. But I understand that most scratch org creates finished within the default wait.

2022-04-13 12:30 UTC, peternhale approved these changes

2022-04-14 14:15 UTC, peternhale submitted a review, later dismissed

2022-04-18 23:17 UTC, RodEsp commented on src/commands/env/create/scratch.ts
> +      flags.async ? 'Requesting Scratch Org (will not wait for completion because --async)' : 'Creating Scratch Org'
@jshackell-sfdc could you review this output too please?

2022-04-19 16:01 UTC, jshackell-sfdc commented on src/commands/env/create/scratch.ts
> +      flags.async ? 'Requesting Scratch Org (will not wait for completion because --async)' : 'Creating Scratch Org'
Okay?  Made the message a bit longer, but hopefully that's still okay.

2022-05-03 00:29 UTC, closed without merging